const mongoose = require("mongoose")

const jobSchema = mongoose.Schema({
    title:{
        type:String,
        required:true,
    },
    description:{
        type:String,
        required:true,
    },
     requirements:[{
        type:String,
        required:true,
    }],
    salary:{
        type:Number,
        required:true,
    },
    location:{
        type:String,
        required:true,
    },
    jobType:{
       type:String,
       required:true,
    },
    experience:{
        type:Number,
        required:true,
    },
    position:{
        type:Number,
        required:true,
    },
    company:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Company",
    },
    createdBy:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"User",
        required:true,
    },
    applications:[
        {
         type:mongoose.Schema.Types.ObjectId,
         ref:"Application"
        }
    ],
    applicants:[
        {
         type:mongoose.Schema.Types.ObjectId,
         ref:"User"
        }
    ]
},{timestamps:true})

module.exports = mongoose.model("Job",jobSchema)